---
title: 10.3.2 方法重写时声明抛出异常的限制
categories: 
  - 疯狂Java讲义 (第4版)
  - 第10章 异常处理
  - 10.3 Checked异常和Runtime异常体系
date: 2019-12-25 05:01:10
updated: 2019-12-25 06:21:16
abbrlink: c0f1bf5
---
<div id='my_toc'><a href="/JavaReadingNotes/c0f1bf5/#10-3-2-方法重写时声明抛出异常的限制" class="header_1">10.3.2 方法重写时声明抛出异常的限制</a>&nbsp;<br><a href="/JavaReadingNotes/c0f1bf5/#Checked异常的缺点" class="header_2">Checked异常的缺点</a>&nbsp;<br><a href="/JavaReadingNotes/c0f1bf5/#推荐使用Runtime异常" class="header_2">推荐使用Runtime异常</a>&nbsp;<br><a href="/JavaReadingNotes/c0f1bf5/#不需要在方法签名中声明中抛出Runtime异常" class="header_2">不需要在方法签名中声明中抛出Runtime异常</a>&nbsp;<br><a href="/JavaReadingNotes/c0f1bf5/#Runtime异常可以使用try-catch捕获" class="header_2">Runtime异常可以使用try-catch捕获</a>&nbsp;<br></div>
<style>.header_1{margin-left: 1em;}.header_2{margin-left: 2em;}.header_3{margin-left: 3em;}.header_4{margin-left: 4em;}.header_5{margin-left: 5em;}.header_6{margin-left: 6em;}</style>
<!--more-->
<script>if (navigator.platform.search('arm')==-1){document.getElementById('my_toc').style.display = 'none';}var e,p = document.getElementsByTagName('p');while (p.length>0) {e = p[0];e.parentElement.removeChild(e);}</script>

<!--end-->
# 10.3.2 方法重写时声明抛出异常的限制
使用`throws`声明抛出异常时有一个限制,就是方法重写时“两小”中的一条规则:**子类方法声明抛出的异常类型应该是父类方法声明抛出的异常类型的子类或相同**,子类方法声明抛出的异常不允许比父类方法声明抛出的异常多。

看如下程序。
```java
import java.io.*;

public class OverrideThrows
{
    public void test()throws IOException
    {
        FileInputStream fis = new FileInputStream("a.txt");
    }
}
class Sub extends OverrideThrows
{
    // 子类方法声明抛出了比父类方法更大的异常
    // 所以下面方法出错
    public void test()throws Exception
    {
    }
}
```
上面程序中`Sub`子类中的`test`方法声明抛出`Exception`,该`Exception`是其父类声明抛出异常`IOException`类的父类,这将导致程序无法通过编译.
## Checked异常的缺点 ##
使用`Checked`异常至少存在如下两大不便之处。
- 对于程序中的`Checked`异常,`Java`要求必须显式捕获并处理该异常,或者显式声明抛出该异常这样就增加了编程复杂度。
- 如果在方法签名中显式声明抛出`Checked`异常,将会导致`方法签名与异常耦合`,如果该方法是`重写父类`的方法,则该方法抛出的异常还会受到被重写方法所抛出异常的限制。

## 推荐使用Runtime异常 ##
在大部分时候推荐使用`Runtime`异常,而不使用`Checked`异常。尤其当程序需要自行抛出异常时,使用`Runtime`异常将更加简洁。
## 不需要在方法签名中声明中抛出Runtime异常 ##
当使用`Runtime`异常时,程序无须在方法中声明抛出`Runtime`异常,一旦发生了自定义错误,程序只管抛出`Runtime`异常即可。
## Runtime异常可以使用try-catch捕获 ##
如果程序需要在合适的地方捕获异常并对异常进行处理,则一样可以使用`try-catch`块来捕获`Runtime`异常。

使用`Runtime`异常是比较省事的方式,使用这种方式既可以享受"正常代码和错误处理代码分离","保证程序具有较好的健壮性"的优势,又可以避免因为使用`Checked`异常带来的编程烦琐性。因此,`C#`、`Ruby`、`Python`等语言没有所谓的`Checked`异常,所有的异常都是`Runtime`异常。

但`Checked`异常也有其优势`Checked`异常能在编译时提醒程序员代码可能存在的问题,提醒程序员必须注意处理该异常,或者声明该异常由该方法调用者来处理,从而可以避免程序员因为粗心而忘记处理该异常的错误。


